default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
        track: 'internal',
        aab: 'app-release.aab',
        skip_upload_apk: true, # We are uploading AAB
    )
    upload_to_play_store(
        track: 'internal',
        track_promote_to: 'beta',
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_changelogs: true,
    )
  end
    lane :production do
      upload_to_play_store(
          track: 'internal',
          track_promote_to: 'production',
          skip_upload_apk: true,
          skip_upload_aab: true,
          skip_upload_changelogs: true,
      )
    end
end
