name: main

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

permissions: {}

jobs:
  checks:
    name: "Checks"
    uses: ./.github/checks.yml

  release-master:
    name: "Release (testing)"
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs: [checks]
    steps:
      - name: Get short SHA
        id: get-short-sha
        run: |
          id=$(echo ${{github.sha}} | cut -c 1-7)
          echo "::set-output name=id::$id"
      - uses: ./.github/release.yml
        with:
          version:  ${{ format('dev-{0}', steps.get-short-sha.outputs.id) }}

  release-tag:
    name: "Release (production)"
    if: github.ref_type == 'tag'
    needs: [checks]
    uses: ./.github/release.yml
    with:
      version: ${{ github.ref_name }}
