name: main

on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

permissions: {}

jobs:
  firestore-tests:
    name: Test Firestore rules
    runs-on: ubuntu-22.04
    container: timbru31/java-node:21-jdk-iron
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        # only enable the cache if the ref is not a tag
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn test

  unit-tests-android:
    name: Unit tests (Android)
    runs-on: ubuntu-22.04
    container: alvrme/alpine-android:android-34-jdk17
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew --no-daemon --parallel testDebugUnitTest

  unit-tests-jvm:
    name: Unit tests (JVM)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Pull rulebooks test data
        if: "! github.event.pull_request.head.repo.fork"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: fmasa/wfrp-master-rulebooks
          token: ${{ secrets.RULEBOOKS_PULL_TOKEN }}
          path: rulebooks
          persist-credentials: false
      - name: Setup Rulebooks test config
        if: "! github.event.pull_request.head.repo.fork"
        run: sed -e "s,{GITHUB_WORKSPACE},$GITHUB_WORKSPACE,g" common/src/jvmTest/resources/config-ci.json > common/src/jvmTest/resources/config.json
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew jvmTest

  ktlint:
    name: Code style (ktlint)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew ktlintCheck

  checks-passed:
    name: Wait for all checks
    needs:
      - unit-tests-android
      - unit-tests-jvm
      - firestore-tests
      - ktlint
    runs-on: ubuntu-22.04
    steps:
      - run: "true"

  release-master:
    name: "Release (testing)"
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs: [checks-passed]
    steps:
      - name: Get short SHA
        id: get-short-sha
        run: |
          id=$(echo ${{github.sha}} | cut -c 1-7)
          echo "::set-output name=id::$id"
      - uses: ./github/release.yml
        with:
          version:  ${{ format('dev-{0}', steps.get-short-sha.outputs.id) }}

  release-tag:
    name: "Release (production)"
    if: github.ref_type == 'tag'
    needs: [checks-passed]
    uses: ./github/release.yml
    with:
      version: ${{ github.ref_name }}
